title: Kevin Carone
logo: /assets/img/profile.jpeg
description: Kevin Carone is a Petroleum Engineer that sees a promising future of machine learning in the Oil & Gas industry
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
