title: Kevin Carone
logo: /assets/img/profile.jpeg
description: Petroleum Engineer that sees a promising future of machine learning in the Oil & Gas industry
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
